= Philosophy
Ian Mackenzie
include::../common.adoc[]

== Introduction

OpenSolid is functionally similar to other vector/geometry packages, but works
differently in a few subtle but meaningful ways. In general, OpenSolid has a
more geometric than mathematical focus. For example, distinct types are used for
points, vectors and directions which many other packages treat as a single
generic vector type.

== Directions

OpenSolid uses the concept of a 'direction' where other packages typically use
vectors with unit length. Having separate types helps to keep track of whether a
vector has already been normalized - no more having to guess whether a function
that accepts a vector argument actually needs a unit vector, and if so whether
you're expected to normalize the vector yourself or whether the function will do
that internally.

You can normalize a vector to produce a direction with the `Vector2d.direction`
and `Vector3d.direction` functions, but they actually return `Maybe` values
since the zero vector has no direction:

[source]
----
Vector2d.direction (Vector2d ( 3, 0 )) ==
    Just (Direction2d ( 1, 0 ))

Vector2d.direction (Vector2d ( -2, 2 )) ==
    Just (Direction2d ( -0.7071, 0.7071 ))

Vector2d.direction (Vector2d ( 0, 0 )) ==
    Nothing
----

This takes advantage of Elm's type system to ensure that all code considers the
degenerate zero-vector case. For example, given an eye point and a point to look
at, the corresponding view direction could be determined with

[source]
----
Vector3d.direction (Point3d.vectorFrom eyePoint lookAtPoint)
----

This would return a `Maybe Direction3d`, with `Nothing` corresponding to the
case where the eye point and point to look at are coincident (in which case the
view direction is not well-defined and some special-case logic is needed).

== Coordinates and components

Explicitly working with individual X/Y/Z point coordinates and vector components
is easy to do in OpenSolid when necessary:

[source]
----
forwardSpeed =
    Vector3d.xComponent velocityVector

height =
    Point3d.zCoordinate position
----

In many cases, however, it is equally easy and often advantageous to consider
points and vectors as abstract geometric quantities and treat their internal
representations by coordinates/components as an implementation detail. For
example, the above might be replaced by

[source]
----
forwardSpeed =
    Vector3d.componentIn forwardDirection velocityVector

height =
    Point3d.signedDistanceFrom groundPlane position
----

where (perhaps in a Constants.elm file or similar) you would define

[source]
----
forwardDirection =
    Direction3d.x

groundPlane =
    Plane3d.xy
----

This approach is less coupled to the particular coordinate system being used and
adapts more easily to changes - perhaps the forward direction becomes a
configuration setting, or the ground plane becomes dynamic and shifts or tilts
over time.
